language: node_js
os: linux
dist: bionic
jobs:
  include:
    - node_js: stable
      name: Test using React 16
    - node_js: stable
      before_script: npm install --no-save react@15 react-dom@15
      name: Test using React 15
    - node_js: stable
      before_script: npm install --no-save react@0.14 react-dom@0.14
      name: Test using React 0.14
    - node_js: 10
      name: Test on Node.js 10
    - node_js: 8
      name: Test on Node.js 8

before_deploy:
  - cd example && npm install && cd ..
  - mkdir _deploy
  - cp example/bundle.js example/index.html _deploy
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: _deploy
  on:
    branch: master
    node: stable
